spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spark_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

flyway:
  baseline-on-migrate: true
  locations: classpath:db/migration
